# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(431, 461)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 10, 191, 151))
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 30, 61, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.car_totle = QtWidgets.QLineEdit(self.groupBox)
        self.car_totle.setGeometry(QtCore.QRect(80, 30, 91, 20))
        self.car_totle.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.car_totle.setObjectName("car_totle")
        self.car_carnum = QtWidgets.QLineEdit(self.groupBox)
        self.car_carnum.setGeometry(QtCore.QRect(110, 60, 61, 20))
        self.car_carnum.setObjectName("car_carnum")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(10, 60, 101, 16))
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(10, 90, 101, 16))
        self.label_5.setObjectName("label_5")
        self.car_terminalnum = QtWidgets.QLineEdit(self.groupBox)
        self.car_terminalnum.setGeometry(QtCore.QRect(110, 90, 61, 20))
        self.car_terminalnum.setObjectName("car_terminalnum")
        self.car_simnum = QtWidgets.QLineEdit(self.groupBox)
        self.car_simnum.setGeometry(QtCore.QRect(80, 120, 91, 20))
        self.car_simnum.setObjectName("car_simnum")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(10, 120, 101, 16))
        self.label_6.setObjectName("label_6")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(220, 10, 191, 151))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(10, 30, 111, 16))
        self.label_2.setObjectName("label_2")
        self.org_carcount = QtWidgets.QLineEdit(self.groupBox_2)
        self.org_carcount.setGeometry(QtCore.QRect(120, 30, 51, 20))
        self.org_carcount.setObjectName("org_carcount")
        self.org_num = QtWidgets.QLineEdit(self.groupBox_2)
        self.org_num.setGeometry(QtCore.QRect(120, 60, 51, 20))
        self.org_num.setObjectName("org_num")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(10, 60, 110, 20))
        self.label_4.setObjectName("label_4")
        self.creatsql_btn = QtWidgets.QPushButton(self.groupBox_2)
        self.creatsql_btn.setGeometry(QtCore.QRect(100, 120, 75, 23))
        self.creatsql_btn.setObjectName("creatsql_btn")
        self.message_show = QtWidgets.QTextBrowser(self.centralwidget)
        self.message_show.setGeometry(QtCore.QRect(20, 170, 391, 241))
        self.message_show.setObjectName("message_show")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 431, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "创建车辆sql"))
        self.groupBox.setTitle(_translate("MainWindow", "车辆参数"))
        self.label.setText(_translate("MainWindow", "总车辆数"))
        self.car_totle.setText(_translate("MainWindow", "10000"))
        self.car_carnum.setText(_translate("MainWindow", "10000"))
        self.label_3.setText(_translate("MainWindow", "车牌初始     测B"))
        self.label_5.setText(_translate("MainWindow", "设备编号初始"))
        self.car_terminalnum.setText(_translate("MainWindow", "1000000"))
        self.car_simnum.setText(_translate("MainWindow", "13100000000"))
        self.label_6.setText(_translate("MainWindow", "SIM初始"))
        self.groupBox_2.setTitle(_translate("MainWindow", "其他"))
        self.label_2.setText(_translate("MainWindow", "每个部门车辆数"))
        self.org_carcount.setText(_translate("MainWindow", "2000"))
        self.org_num.setText(_translate("MainWindow", "801"))
        self.label_4.setText(_translate("MainWindow", "部门起始编号B0000"))
        self.creatsql_btn.setText(_translate("MainWindow", "生成sql"))

