# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(888, 878)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(10, 710, 391, 121))
        self.textEdit.setObjectName("textEdit")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(490, 10, 311, 16))
        self.label_2.setObjectName("label_2")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(490, 40, 391, 791))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(180)
        self.Button_apart = QtWidgets.QPushButton(self.centralwidget)
        self.Button_apart.setGeometry(QtCore.QRect(410, 710, 75, 23))
        self.Button_apart.setObjectName("Button_apart")
        self.Button_join = QtWidgets.QPushButton(self.centralwidget)
        self.Button_join.setGeometry(QtCore.QRect(410, 740, 75, 23))
        self.Button_join.setObjectName("Button_join")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget_2.setGeometry(QtCore.QRect(890, 20, 361, 811))
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(2)
        self.tableWidget_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        self.tableWidget_2.horizontalHeader().setDefaultSectionSize(170)
        self.Button_send = QtWidgets.QPushButton(self.centralwidget)
        self.Button_send.setGeometry(QtCore.QRect(410, 770, 75, 23))
        self.Button_send.setObjectName("Button_send")
        self.textEdit_log = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_log.setGeometry(QtCore.QRect(10, 40, 471, 101))
        self.textEdit_log.setObjectName("textEdit_log")
        self.lineEdit_IP = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_IP.setGeometry(QtCore.QRect(30, 10, 113, 20))
        self.lineEdit_IP.setObjectName("lineEdit_IP")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 21, 16))
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(170, 10, 31, 16))
        self.label_3.setObjectName("label_3")
        self.lineEdit_port = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_port.setGeometry(QtCore.QRect(210, 10, 41, 20))
        self.lineEdit_port.setObjectName("lineEdit_port")
        self.Button_conn = QtWidgets.QPushButton(self.centralwidget)
        self.Button_conn.setGeometry(QtCore.QRect(270, 10, 75, 23))
        self.Button_conn.setObjectName("Button_conn")
        self.Button_disconn = QtWidgets.QPushButton(self.centralwidget)
        self.Button_disconn.setGeometry(QtCore.QRect(360, 10, 75, 23))
        self.Button_disconn.setObjectName("Button_disconn")
        self.textEdit.raise_()
        self.label_2.raise_()
        self.tableWidget.raise_()
        self.Button_apart.raise_()
        self.Button_join.raise_()
        self.tableWidget_2.raise_()
        self.Button_send.raise_()
        self.lineEdit_IP.raise_()
        self.label.raise_()
        self.label_3.raise_()
        self.lineEdit_port.raise_()
        self.Button_conn.raise_()
        self.Button_disconn.raise_()
        self.textEdit_log.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 888, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">7E 02 00 40 55 01 00 00 00 00 01 38 01 80 42 79 00 4E 00 80 00 00 00 00 10 11 00 00 00 00 00 00 00 00 00 00 00 00 00 00 19 08 23 10 55 28 01 04 00 01 2F 50 02 02 00 00 03 02 00 00 31 01 00 14 04 00 00 00 00 30 01 36 F0 01 03 F1 0A 30 8C AC 53 24 4F 18 00 74 8C F2 01 00 F3 02 03 63 F4 04 00 07 F1 FF E1 01 8B EC 7E</p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "________说明  _D:十进制, _B:二进制________"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "名"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "值"))
        self.Button_apart.setText(_translate("MainWindow", "解  析"))
        self.Button_join.setText(_translate("MainWindow", "合  成"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "name"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "value"))
        self.Button_send.setText(_translate("MainWindow", "发  送"))
        self.lineEdit_IP.setText(_translate("MainWindow", "192.168.3.161"))
        self.label.setText(_translate("MainWindow", "IP"))
        self.label_3.setText(_translate("MainWindow", "端口"))
        self.lineEdit_port.setText(_translate("MainWindow", "5560"))
        self.Button_conn.setText(_translate("MainWindow", "连接"))
        self.Button_disconn.setText(_translate("MainWindow", "断开"))

